### ISSUE TITLE
Tooltip is being overlapped even with "flip" specified

### ISSUE THREAD

**Issue by GabrielBarcelos1** [ariakit/ariakit#2189] opened 2023-01-04 18:11 UTC
### Current behavior

the tooltip is not respecting the screen size depending on the position it is in.

if the anchor is to the left or right side of the screen it is overlapped

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/competent-saha-x4bnq8
2. Resize the screen to see the tooltip problem

### Expected behavior

1. Open sandbox: https://codesandbox.io/s/competent-saha-x4bnq8
2. Go to `sytles.css`
3. Change from `justify-content: end` to `justify-content: center` to see working properly

### Workaround

https://github.com/ariakit/ariakit/issues/2189#issuecomment-1371347521

**Comment by diegohaz** [comment] 2023-01-04 19:46
Looks like that's a problem with the centered placement. It works if you use `bottom-end` instead.

**Comment by GabrielBarcelos1** [comment] 2023-01-04 20:13
It depends which is the use case.

for example, if the anchor is on the left and the tooltip opens to the right only `bottom-start` works

[codesandbox representing](https://codesandbox.io/s/fervent-agnesi-czcmq0?file=/src/App.tsx)

**Comment by georgekaran** [comment] 2023-01-05 13:53
> Looks like that's a problem with the centered placement. It works if you use `bottom-end` instead.

Hey @diegohaz, thanks for the kick workaround. Do you think this is something related to the `floating-ui` lib? If so, we could report this bug to them

**Comment by diegohaz** [comment] 2023-01-05 14:02
@georgekaran That may be related to Floating UI, yes. We simply convert this string to an array and pass it to the [`fallbackPlacements`](https://floating-ui.com/docs/flip#fallbackplacements) option on the [`flip`](https://floating-ui.com/docs/flip) middleware:

https://github.com/ariakit/ariakit/blob/4974610b574d91b192fd2d970e3592bb98f994f3/packages/ariakit/src/popover/popover-state.ts#L161-L181

If this issue can be reproduced using only Floating UI, it's probably better to fix it there.

**Comment by atomiks** [comment] 2023-01-05 15:48
It looks like it's due to the ordering of `flip` and `shift`. The reason is the floating element can't fit on either placement properly. By putting `shift` first, `flip` then recognizes that it fits on both axes because `shift` performed its work successfully already and makes it act like `bottom-end` (which is why that works, too):

https://codesandbox.io/s/floating-ui-react-dom-template-forked-grbiqb?file=/src/App.js

Of course, the ordering of `shift` and `flip` then becomes a problem if you want an edge aligned placement to flip to the opposite alignment before `shift`. 

Disabling `crossAxis` checking in `flip` also works and allows `shift` to stay in the same order, but again, `flipAlignment` then no longer works. So I feel like doing something like `crossAxis: placement.includes('-')` might be a good idea?

**Comment by atomiks** [comment] 2023-01-29 08:56
After investigating more, this is actually a bug in Floating UI and you shouldn't need to do the above. I've made a PR to fix, linked above^

**Comment by atomiks** [comment] 2023-01-29 10:13
I verified it works locally with Ariakit and it's now releasing as `@floating-ui/core@1.1.1`, but one thing to note: adding `max-width: calc(100vw - 2 * SHIFT_PADDING)` will ensure the right side has padding. 

I guess this should be an inline style done via Ariakit, because it has to target the root (presentational) floating node, which is a parent of the tooltip? Unless the user can target this themselves somehow:

<img width="507" alt="Demo of tooltip flipped to bottom with Ariakit, but no padding on the right side" src="https://user-images.githubusercontent.com/22450188/215319122-90e37225-a5c7-4b61-a989-b7598ca671a2.png">

**Comment by diegohaz** [comment] 2023-06-27 20:09
Closing as this has been fixed upstream.

Users can use the [`--popover-available-width`](https://ariakit.org/guide/styling#--popover-available-width) or [`--popover-overflow-padding`](https://ariakit.org/guide/styling#--popover-overflow-padding) CSS variables to style `max-width`.

**Closed by diegohaz** 2023-06-27 20:09 UTC
Labels: bug, has workaround
