### ISSUE TITLE
Tooltip doesn't recalculate placement on inner text change

### ISSUE THREAD

**Issue by nkrantz** [ariakit/ariakit#931] opened 2021-11-10 22:58 UTC
### Current behavior

When using Tooltip, if the length of the inner text changes while the tooltip is open, the alignment is no longer centered. Once the tooltip closes and re-opens, it's aligned correctly again. There's a workaround using `useEffect()` watching the tooltip text, so when it changes, the tooltip's `.hide()` and `.show()` are called.

### Steps to reproduce the bug

1. Codesandbox: https://codesandbox.io/s/musing-phoebe-ih385?file=/src/index.tsx
2. See current behavior in first example - hover over the button and 

### Expected behavior

When the tooltip text changes, the placement should be recalculated so that the text stays centered with the tooltip arrow.

**Comment by diegohaz** [comment] 2021-11-11 05:24
Thanks for the thorough reproduction @nkrantz!

This is a feature that we're planning to make stable in the next versions. For now, your workaround looks okay. Alternatively, you can also run the experimental `tooltip.unstable_update()`  when the tooltip content is updated:

```jsx
useEffect(tooltip.unstable_update, [text]);
```

The method name will change in future versions, but we'll probably not support an automatic recalculation by default because this could degrade performance for those who don't need this feature.

**Comment by charleneyjh1** [comment] 2021-12-07 19:27
Thank you for your response, @diegohaz !
I wonder do you have a rough timeline on when this fix gonna happen? Knowing this will help our team prioritize our work, thank you!

**Comment by diegohaz** [comment] 2021-12-07 19:38
> Thank you for your response, @diegohaz ! I wonder do you have a rough timeline on when this fix gonna happen? Knowing this will help our team prioritize our work, thank you!

@charleneyjh1 What kind of "fix" do you expect? As I said, it's probably never going to happen automatically, unless we find a way to do this without any performance impact, which I'm afraid we won't.

If you're talking about the `unstable_update()` *feature*, there's no date. If that's something urgent, I'd say just use this method and follow the instructions on https://reakit.io/docs/experimental/.

**Comment by ntkoopman** [comment] 2022-02-22 02:19
I've been using `requestAnimationFrame` and `getBoundingClientRect` for positioning for my own components and it's not really a performance issue because `getBoundingClientRect` is cached if nothing has changed. Advantage is that it's always in the right position, no matter what caused the change. And most of these components are only on the page for a short duration anyway.

**Comment by atomiks** [comment] 2022-04-07 11:30
@diegohaz I know Ariakit is still on Popper but it'd be great to upgrade to Floating UI before the final v2 release.

There are options for this that works performantly: https://floating-ui.com/docs/autoUpdate

The situation described by @nkrantz is the `ResizeObserver` case. The one described by @ntkoopman is `animationFrame` (and is also optimized).

**Comment by diegohaz** [comment] 2022-04-28 03:06
Closing as this will be fixed in v2 thanks to Floating UI.

**Closed by diegohaz** 2022-04-28 03:06 UTC
Labels: potential bug, has workaround
