### ISSUE TITLE
Custom combobox doesn't always show ComboboxPopover on focus

### ISSUE THREAD

**Issue by jasikpark** [ariakit/ariakit#2608] opened 2023-06-30 20:15 UTC
### Current behavior

When I click into my custom combobox, the popover only shows after I have typed a character and pressed backspace, rather than on initial focus. If I log the combobox store value, I can see that the popover *does* contain values, but that some of them have `hidden=""` attributes on the html

### Steps to reproduce the bug

reproduction WIP, here's a screenrecording in the meantime:

https://github.com/ariakit/ariakit/assets/10626596/b32364ab-90f5-43c3-ac37-f24a12cb0fcf

This may be a symptom of using it controlled by react-hook-form?

### Expected behavior

If there is a child of the ComboboxPopover when rendered and the input is focused, the popover should be rendered, like in https://ariakit.org/components/combobox

**Comment by diegohaz** [comment] 2024-02-21 23:40
Closing because we couldn't reproduce the issue. We'll reopen it if a repro is provided.

**Closed by diegohaz** 2024-02-21 23:40 UTC
Labels: can't reproduce, potential bug
