### ISSUE TITLE
Nested dialogs don't remove inert attribute when closed

### ISSUE THREAD

**Issue by Dremora** [ariakit/ariakit#2503] opened 2023-06-01 21:30 UTC
### Current behavior

Under a very specific set of conditions, closing nested modals doesn't seem to fully clean up changes made to the page - namely, `inert` attribute is still applied to the top level elements. The conditions are following:

- Two modals need to exist one inside the other
- Both modals need to have `getPersistentElements` property with at least one element
- Inner modal needs to have a Tooltip
- After a modal is unmounted, it needs to be removed from DOM

Strangely enough, removing any of the conditions from above resolves the bug.

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/oqajjb?file=app%2Fdialog-nested%2Findex.tsx,app%2Fdialog-nested%2Fconfirm-dialog.tsx,app%2Flayout.tsx,app%2Fpage.tsx&theme=dark
2. Press View Cart to open 1st dialog
3. Press any of the Remove buttons to open 2nd dialog
4. Close the 2nd dialog by pressing outside
5. Close the 1st dialog by pressing outside

### Expected behavior

"View Cart" button is interactive

### Workaround

Relaxing any of the conditions from the initial list helps.

**Comment by Dremora** [comment] 2023-06-01 21:34
Likely a duplicate of #2501, when I was writing this bug report, the other one didn't exist! 😅

**Comment by diegohaz** [comment] 2023-06-02 01:41
Thanks for taking the time to debug this and report @Dremora!

Yes, that's likely the same issue. I'll close this as a duplicate of #2501. If the solution to that issue doesn't solve this one, we can reopen it.

**Closed by diegohaz** 2023-06-02 01:41 UTC
Labels: potential bug
