### ISSUE TITLE
Popover with "portal" prop true is not positioned correctly 

### ISSUE THREAD

**Issue by hyanmandian** [ariakit/ariakit#1872] opened 2022-09-19 17:18 UTC
### Current behavior

When we use Popover or any other component that uses popover behind the scenes with `portal` prop true and the anchor parent has scroll, if you scroll this content the popover position is not getting updated.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/strange-surf-q9bhdh?file=/index.js
2. Click on the trigger and scroll the page

### Expected behavior

The expected behavior is to update with the correct position as it did with the `portal` false

### Workaround

https://github.com/ariakit/ariakit/issues/1872#issuecomment-1251333863

**Comment by diegohaz** [comment] 2022-09-19 17:37
Thanks for reporting.

As a workaround, you can add `onScroll={popover.render}` to the scrollable element.

**Comment by hyanmandian** [comment] 2023-05-04 12:17
Hey @diegohaz I forgot to mention, but here is my workaround for it following your suggestion:

```ts
const OVERFLOW_REGEX = /(auto|scroll)/;

export const getScrollableParent = (
  el: HTMLElement | null,
  axe: "x" | "y" = "y"
): HTMLElement | null => {
  while (el && el.parentElement) {
    const { overflow, overflowY, overflowX } = getComputedStyle(
      el.parentElement
    );

    const isXScrollable = OVERFLOW_REGEX.test(overflowX);
    const isYScrollable = OVERFLOW_REGEX.test(overflowY);
    const isBothScrollable = OVERFLOW_REGEX.test(overflow);

    if (
      (isYScrollable && axe === "y") ||
      (isXScrollable && axe === "x") ||
      isBothScrollable
    ) {
      return el.parentElement;
    }

    el = el.parentElement;
  }

  return null;
};

export const usePopoverWorkaround = (
  ref: RefObject<HTMLElement>,
  popover: PopoverStore
) => {
  const isFirstRenderRef = useRef(true);

  const isOpen = popover.useState("open");
  const render = popover.render;

  const onParentScroll = useEvent(() => {
    if (isOpen) popover.render();
  });

  useEffect(() => {
    if (isFirstRenderRef.current && isOpen) {
      render();
      isFirstRenderRef.current = false;
    }
  }, [render, isOpen]);

  useEffect(() => {
    const parent = getScrollableParent(ref.current);

    parent?.addEventListener("scroll", onParentScroll);

    return () => parent?.removeEventListener("scroll", onParentScroll);
    /**
     * We don't need to track onScroll since its reference doesn't change
     */
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
};
```

**Comment by MarosPistej** [comment] 2023-06-18 16:42
Not sure if `Select` use portal but certainly it has this issue viz. video, if select open to one direction it doesn't want to update to other 

https://github.com/ariakit/ariakit/assets/43110161/af877f80-562e-48c9-9f3e-706c68dfb84c

**Comment by diegohaz** [comment] 2023-06-18 23:16
@MarosPistej that looks like a different bug. Could you please open a separate issue?

**Comment by diegohaz** [comment] 2023-06-19 00:27
I actually can't reproduce the original behavior reported in this issue anymore. So I guess it might have been fixed in Floating UI.

**Closed by diegohaz** 2023-06-19 00:27 UTC
Labels: feature, has workaround
