### ISSUE TITLE
`Tab`: Test outputs `act` warning on first render with `@ariakit/react` > `0.3.12`

### ISSUE THREAD

**Issue by ciampo** [ariakit/ariakit#3939] opened 2024-07-12 11:28 UTC
### Current behavior

While testing `Ariakit.Tab` with `jest` and `@testing-library/react`, an "An update to [...] inside a test was not wrapped in act(...)." warning is logged to the console.

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/xcwcc5 and install dependencies
2. Run `jest` in the terminal
3. Observe the output

### Expected behavior

No warning should be logged

### Workaround

No workaround found

### Possible solutions

It looks like this was introduced from `@ariakit/react` version `0.3.13`.

- running the test with version `0.3.12` doesn't cause any warnings
- the warning is still present in the latest version as of today (`0.4.7`)

This could be likely related to https://github.com/ariakit/ariakit/pull/3295 and therefore related to all collection-based components.

**Comment by ciampo** [comment] 2024-07-12 11:28
cc @DaniGuardiola

**Comment by diegohaz** [comment] 2024-07-12 12:25
RTL `render` is synchronous and does not fully mimic real browser behavior. Any timer (`rAF`, `rIC`, `setTimeout`, etc.) scheduled on the first render of a component will trigger an act warning. This behavior may change in Ariakit with patch or minor versions since it's not a breaking change.

With RTL, you will need to `waitFor` something in the DOM immediately after calling `render`.

In Ariakit, we use our own `render` utility from `@ariakit/test/react`, which is asynchronous and accounts for those timers.

**Comment by diegohaz** [comment] 2024-07-12 12:42
> ### Steps to reproduce the bug
> 1. Open https://stackblitz.com/edit/xcwcc5 and install dependencies
> 2. Run `jest` in the terminal
> 3. Observe the output

Fork using async render from `@ariakit/test/react`: https://stackblitz.com/edit/xcwcc5-qp6yyr?file=test%2Findex.test.tsx

**Comment by ciampo** [comment] 2024-07-12 13:01
Thank you @diegohaz for the quick reply.

> With RTL, you will need to `waitFor` something in the DOM immediately after calling render.

I guess this is that we were already doing [in `Composite` tests](https://github.com/WordPress/gutenberg/blob/decaae66b0e4ca173b1bbb1ee7a059819074a918/packages/components/src/composite/legacy/test/index.tsx#L44-L55), right?

> In Ariakit, we use our own render utility from @ariakit/test/react, which is asynchronous and accounts for those timers.

That's great! I didn't see that documented anywhere, thank you for pointing it out.

**Comment by donaldpipowitch** [comment] 2024-07-23 14:25
Wow, I was pulling my hairs out in the last hour 😆  We have thousands of tests and a **single** one of them apparently needed this. I experienced it during the initial render of a select from ariakit. I couldn't really find something regarding this in the docs when I search for "test".

And while `@ariakit/test` is written in TypeScript there seems to be a problem with the typings. I couldn't load `@ariakit/test/react` right away, I needed to create my own type definition for it. But it seems to work. Thank you @diegohaz.

**Comment by DaniGuardiola** [comment] 2024-07-23 17:29
@diegohaz think it'd be worth it making the test package public and adding docs on the website? Seems like this could become a common issue for users.

**Comment by diegohaz** [comment] 2024-07-23 21:10
> And while `@ariakit/test` is written in TypeScript there seems to be a problem with the typings. I couldn't load `@ariakit/test/react` right away, I needed to create my own type definition for it. But it seems to work. Thank you @diegohaz.

@donaldpipowitch It should work. Could you reproduce that in StackBlitz or CodeSandbox?

**Comment by donaldpipowitch** [comment] 2024-07-24 06:32
@diegohaz After re-installing it seems to work now. Strange. 🤔 But happy that it works.

**Comment by DaniGuardiola** [comment] 2024-07-25 19:16
FYI, I tested whether using the `render` method multiple times in a test properly re-renders in the same React tree, and whether React trees are kept separate between different tests. The answer is positive for both, which means that it can replace the react testing library `rerender` method.

See sandbox (run `jest` in console): https://stackblitz.com/edit/xcwcc5-wekcbk?file=test%2Findex.test.tsx&view=editor

I would suggest making `render` return `Promise<{ rerender: typeof render }>` where `rerender` is itself (`render`). This would mimic the react testing library behavior and help migrate for those who need it. It's also convenient and semantic, IMO.

**Comment by DaniGuardiola** [comment] 2024-07-25 19:16
FYI, I tested whether using the `render` method multiple times in a test properly re-renders in the same React tree, and whether React trees are kept separate between different tests. The answer is positive for both, which means that it can replace the react testing library `rerender` method.

See sandbox (run `jest` in console): https://stackblitz.com/edit/xcwcc5-wekcbk?file=test%2Findex.test.tsx&view=editor

I would suggest making `render` return `Promise<{ rerender: typeof render }>` where `rerender` is itself (`render`). This would mimic the react testing library behavior and help migrate for those who need it. It's also convenient and semantic, IMO.

**Comment by DaniGuardiola** [comment] 2024-07-25 20:18
Update: I managed to create a scenario where an "act" warning is triggered even though the `render` function from Ariakit is the only thing being used, in case it's helpful: https://stackblitz.com/edit/xcwcc5-k9mk85?file=test%2Findex.test.tsx&view=editor

**Comment by DaniGuardiola** [comment] 2024-07-25 20:23
Update 2: it seems like the re-rendering stuff is not as straightforward as I thought. After running into a similar issue in Gutenberg, I managed to create this repro: https://stackblitz.com/edit/xcwcc5-ahxwrq?file=test%2Findex.test.tsx&view=editor

Notice how the value, which should be reflected in the DOM, is stale.

**Comment by DaniGuardiola** [comment] 2024-07-25 22:22
Update: in a local fork, I implemented re-render support in this utility and it works very well. See https://github.com/WordPress/gutenberg/commit/bac40268878fb9ae4e0b876920dc5f488b015087 for specific changes, it's quite straightforward!

Could we add this here? Happy to contribute it, just need your approval @diegohaz in case you have a better idea.

**Comment by diegohaz** [comment] 2024-07-26 04:46
> I've discovered that `render` doesn't actually re-render, and it only creates a different tree. Here's a repro: https://stackblitz.com/edit/xcwcc5-ahxwrq?file=test%2Findex.test.tsx&view=editor

@DaniGuardiola Thanks for testing it. An easier workaround is to pass the same `container` to both `render` calls (you may need to call `screen.getByRole` again on the repro you provided instead of reusing `element`):

```jsx
const container = document.createElement("div");
document.body.appendChild(container);

await render(<Comp value="a" />, { container });
await render(<Comp value="b" />, { container });
```

> I managed to create a scenario where an "act" warning is triggered even though the `render` function from Ariakit is the only thing being used, in case it's helpful: https://stackblitz.com/edit/xcwcc5-k9mk85?file=test%2Findex.test.tsx&view=editor

Yeah! I think waiting for timeouts after a paint might be too much, but we can support it if there's a valid use case.

**Comment by DaniGuardiola** [comment] 2024-07-29 19:47
@diegohaz to summarize and update you on where I stand.

- There is no need to alter the wait time, we didn't need to do this in our tests.
- My local fork of the `render` utility does the following:
  - Return the output of the internal RTL `render` call entirely, instead of just `unmount`.
  - Wrap the `rerender` function in the same "waiting logic" as `render`.
- The use of `rerender` is widespread in our tests.
- We also use some other parts of the output of RTL's `render`.

Because of this, what currently would work best is to apply these changes in Ariakit so we can use the upstream version. I'll be happy to drive the PR to make this happen.

Does this sound okay?

**Comment by diegohaz** [comment] 2024-07-29 19:58
> @DaniGuardiola Thanks for testing it. An easier workaround is to pass the same `container` to both `render` calls (you may need to call `screen.getByRole` again on the repro you provided instead of reusing `element`):
> 
> ```js
> const container = document.createElement("div");
> document.body.appendChild(container);
> 
> await render(<Comp value="a" />, { container });
> await render(<Comp value="b" />, { container });
> ```

Does this work for you? Because we can potentially simplify the implementation of this rerender method so it doesn't rely on RTL internally. In the future, we'll likely remove the RTL dependency altogether.

**Comment by DaniGuardiola** [comment] 2024-07-29 20:11
@diegohaz it unfortunately does not without a very large amount of changes at best, or directly being incompatible with our current tests at worst:

- We'd need to rewrite all `rerender` instances to use this pattern.
- As you said, we'd potentially need to query elements again instead of re-using existing references, which is not only a big rewrite, but in some cases the point of the test (checking that an element has been properly updated or disconnected from the DOM).
- We also use other parts of the RTL `render` output. I looked for the ones I saw but couldn't find them though, unfortunately.

Is the approach I'm proposing fundamentally incompatible with the direction of this library? I think the plan to remove RTL entirely could be a sign of this, since we still use things like `screen` from it and I'm not sure it'd work anymore in this case (or maybe it would if it only depends on the DOM backend like JSDOM? I don't know enough about this :P).

**Comment by diegohaz** [comment] 2024-07-29 20:29
> * As you said, we'd potentially need to query elements again instead of re-using existing references, which is not only a big rewrite, but in some cases the point of the test (checking that an element has been properly updated or disconnected from the DOM).

I quickly reviewed the RTL code and thought the only difference between `render` and `rerender` was the reuse of the container element. I might have missed something. Still, I wish our `rerender` method didn't rely on RTL if it's possible.

> Is the approach I'm proposing fundamentally incompatible with the direction of this library? I think the plan to remove RTL entirely could be a sign of this, since we still use things like `screen` from it and I'm not sure it'd work anymore in this case (or maybe it would if it only depends on the DOM backend like JSDOM? I don't know enough about this :P).

`@ariakit/test` has a different query API (exposed as `q`, [here's an example](https://github.com/ariakit/ariakit/blob/0dc620f15b2371ea7b0a3d101ea5d14c75ffed0a/examples/tag/test.ts)). In summary, `@ariakit/test` won't follow RTL's API. I'm not opposed to `render` returning `{ unmount, rerender }`, but I don't think returning the entire RTL output is a good idea at this point.

**Comment by DaniGuardiola** [comment] 2024-07-30 12:59
> I'm not opposed to `render` returning `{ unmount, rerender }`

Alright, I tested it and it works for us so far. Let's compromise on that and ship a version so I can undo my temporary local fork in the Gutenberg repo, if that sounds good. See: https://github.com/WordPress/gutenberg/pull/64066/commits/db1d47832ee11e7c7d6ccf73dc0d8e5aa5f79829

> `@ariakit/test` has a different query API (exposed as `q`, [here's an example](https://github.com/ariakit/ariakit/blob/0dc620f15b2371ea7b0a3d101ea5d14c75ffed0a/examples/tag/test.ts))

Right, then if in the future you remove RTL, we will need to consider whether to go all-in with `@ariakit/test` and replace RTL queries with this. FWIW, that sounds good to me, I think `@ariakit/test` is a great RTL replacement in many ways, namely the `render` and event trigger waits and the better query API.

We'd need to discuss in the team when the time comes, and `@ariakit/test` would need to become somewhat stable for it to be worth it probably. Anyway, that's for the future, and in the worst case we can always simply fork, so it shouldn't affect our short-term decisions.

**Comment by diegohaz** [comment] 2024-07-30 13:33
> Right, then if in the future you remove RTL, we will need to consider whether to go all-in with `@ariakit/test` and replace RTL queries with this.

It's worth noting that even if Ariakit Test removes the RTL dependency, RTL queries will still work on trees rendered by Ariakit Test and vice versa. Queries depend solely on the DOM (either JSDOM or the browser).

**Comment by benrodrs** [comment] 2024-08-10 10:15
Closing since the original question seems to be answered (RTL's `render` does not account for microtasks/timers).

**Closed by benrodrs** 2024-08-10 10:15 UTC
Labels: question
