### ISSUE TITLE
When animated: false, MenuItem onClicks stop working in 0.4.0

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#3388] opened 2024-01-25 20:44 UTC
### Current behavior

When I set animated: false on my menuStore, MenuItem onClick handlers stop working.

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/ariakit?devToolsHeight=33&file=src%2FApp.tsx
2. Remove any line
3. See console logs

### Expected behavior

Should click right.

**Comment by httpete** [comment] 2024-01-25 20:45
It very much be related to running the Menus in a portal and portalRef.

**Comment by httpete** [comment] 2024-01-25 20:59
Trying here Diego - I am using the render prop in mine. I wonder if that makes the diff.
https://codesandbox.io/p/sandbox/ariakit-forked-mqm56w?file=%2Fstyle.css%3A248%2C15

**Comment by diegohaz** [comment] 2024-01-25 21:08
Could you share a video showing what's happening?

**Comment by httpete** [comment] 2024-01-25 21:17
https://github.com/ariakit/ariakit/assets/1200635/8e0f0a73-96e0-457d-a2e5-a4076e773d00

you can see the first menu work np. The second (last one) that is rendered with the same component won't.
If I remove the css , the links work.

**Comment by httpete** [comment] 2024-01-25 21:40
I have evidence that it is related to the portalRef. If it isnt in a portalRef, it works.

**Comment by httpete** [comment] 2024-01-25 23:19
I have a workaround for anyone that needs. On my menu I have this which allows the link to work, even with the css selector applied to stop the data-leave transition.
```
              onMouseDown={e => e.preventDefault()}

**Comment by diegohaz** [comment] 2024-01-29 14:51
I'm going to close this since we can't move forward without a reproducible example. If someone provides one, we'll reopen it.

**Closed** 2024-01-29 14:52 UTC
Labels: can't reproduce, potential bug

**Comment by httpete** [comment] 2024-01-29 16:29
Yes I agree and thanks @diegohaz . It must be something specific to my use case and environment, I can't reproduce it outside. Thank you.
