### ISSUE TITLE
Add a slider component (range input)

### ISSUE THREAD

**Issue by mule-stand** [ariakit/ariakit#2694] opened 2023-08-04 13:50 UTC
### Motivation

This is a frequently used and rather complex low-level primitive that will fit in well 

### Usage example

https://mui.com/material-ui/react-slider/

### Requirements

https://mui.com/material-ui/react-slider/

**Comment by diegohaz** [comment] 2023-08-04 14:27
Duplicate of #2100

**Closed by diegohaz** 2023-08-04 14:27 UTC
Labels: duplicate, feature
